// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzySKC5Q4T1gv0oTGxVZBRc12Qj_NCJOE',
    appId: '1:549972438647:web:40ac2517931303b495a072',
    messagingSenderId: '549972438647',
    projectId: 'sessizsehir-852d2',
    authDomain: 'sessizsehir-852d2.firebaseapp.com',
    storageBucket: 'sessizsehir-852d2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxjGXwosh8oikiWR6gMUyhcJrJExc9gpY',
    appId: '1:549972438647:android:c6130ab26eb82e1495a072',
    messagingSenderId: '549972438647',
    projectId: 'sessizsehir-852d2',
    storageBucket: 'sessizsehir-852d2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2XAkCavdbSAOeZ8BF2fzWkrV0ZzMILEQ',
    appId: '1:549972438647:ios:391a5a3205c84b4e95a072',
    messagingSenderId: '549972438647',
    projectId: 'sessizsehir-852d2',
    storageBucket: 'sessizsehir-852d2.appspot.com',
    iosBundleId: 'com.example.sesizzSehir',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2XAkCavdbSAOeZ8BF2fzWkrV0ZzMILEQ',
    appId: '1:549972438647:ios:7d8727d557c836a595a072',
    messagingSenderId: '549972438647',
    projectId: 'sessizsehir-852d2',
    storageBucket: 'sessizsehir-852d2.appspot.com',
    iosBundleId: 'com.example.sesizzSehir.RunnerTests',
  );
}
